sudo: required
dist: trusty
language: node_js
node_js:
  - '8.4'

branches:
  only:
  - master

before_script:
  - npm install -g --silent @angular/cli
  - npm install -g --silent karma
  - npm install
  - ng build